name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test_lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.18', '1.19' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run library go tests
        run: cd lib; go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

  test_stores:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.18', '1.19' ]
        store:
        - bigcache
        - freecache
        - go_cache
        - memcache
        - pegasus
        - redis
        - rediscluster
        - ristretto
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run stores go tests
        run: cd store/${{ matrix.store }}; go test -v -race ./...
